### ISSUE TITLE
Clean up argument code

### ISSUE THREAD

**Issue by JamesWilmot** [beauraines/toggl-cli#15]
This tool is an excellent idea and thanks for all the effort you have put into it!

Would there be any interest in cleaning up the argument parsing code? What I would like to do is make it simpler to add command line options. Currently the if/else ladder makes this a tad difficult and clumsy; not an entirely sustainable solution. 

Thanks heaps!

James

**Comment by beauraines** [comment]
Closing in favor of the updates to https://github.com/AuHau/toggl-cli
